services:
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_TCP_PORT=$DATABASE_PORT
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    volumes:
      - db:/var/lib/mysql
  web:
    container_name: "web"
    working_dir: /web
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/web
volumes:
  db:
