# ========= Development ========= # 
run:
	go run ./cmd/web start

compose-build:
	docker compose -p puzzlely build web

compose-up:
	docker compose -p puzzlely up --build web

compose-run:
	docker compose -p puzzlely up web

compose-down:
	docker compose -p puzzlely down
