services:
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
    volumes:
      - db:/var/lib/postgresql/data
  api:
    working_dir: /api
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - .:/api
volumes:
  db:
