version: "3.8"
services:
  dev:
    working_dir: /puzzlely
    container_name: "puzzlely_dev"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/puzzlely
