# ========= Development ========= # 
run:
	go run ./cmd/web start

dev-build:
	docker compose -p puzzlely build web

dev-up:
	docker compose -p puzzlely up --build web

dev-run:
	docker compose -p puzzlely up web

dev-down:
	docker compose -p puzzlely down
