# ========= Development ========= # 
run:
	go run ./cmd start

compose-build:
	docker-compose -p puzzlely build dev

compose-up:
	docker-compose -p puzzlely up --build dev

compose-run:
	docker-compose -p puzzlely up dev

compose-down:
	docker-compose -p puzzlely down
