name: Build and Push to Docker Hub
on:
  push:
    branches:
      - main
    paths: 
      - api/**
      - web/**
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - id: filter
      name: Filter changed paths
      uses: dorny/paths-filter@v2
      with:
        filters: |
          api:
            - api/**
          web:
            - web/**
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Only run if API files were changed
    - if: steps.filter.outputs.api == 'true'
      name: Build and push API to Docker
      uses: docker/build-push-action@v3
      with:
        context: ./api
        file: "{context}/docker/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/puzzlely:api
    # Only run if Web files were changed
    - if: steps.filter.outputs.web == 'true'
      name: Build and push Web to Docker
      uses: docker/build-push-action@v3
      with:
        context: ./web
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/puzzlely:web
